language: csharp
solution: SOEN341-QAWebsite.sln

sudo: required

before_install:
  - chmod +rwx build.sh

dotnet: 1.0.0-preview2-003121

mono: none

script:  
  - dotnet --info
    - ./build.sh
    
